theme: jekyll-theme-minimal
title: E Cedric Corro
description: This site contains a collection of data science projects that I did individually or with a team.
<p style="font-size:80%><span class="a">Fields of study</span> <span class="b">:</span> <span class="c">"Mathematics and Data Science"</span></p>
<p style="font-size:80%><span class="a">E-mail</span> <span class="b">:</span> <span class="c">"euced.corro@gmail.com"</span></p>
<p style="font-size:80%><span class="a">Location</span> <span class="b">:</span> <span class="c">"Makati City, Philippines"</span></p>
logo: /prof_pic/img.jpg

baseurl: /euced.github.io
