theme: jekyll-theme-minimal
title: E Cedric Corro
description: This site is a contains a collection of data science projects that I did either individually or with a team.
logo: euced.github.io/profpic
