theme: jekyll-theme-minimal
title: E Cedric Corro
description: This site contains a collection of data science projects that I did individually or with a team. I am a former university mathematics instructor for 3 years with a formal postgraduate training in mathematics, data science and business analytics.
logo: /prof_pic/img.jpg

baseurl: /euced.github.io
